// Tests/ImperumCoreTests/ClipCaptureTests.swift
import XCTest
@testable import ImperumCore

/// Tracks whether `rtf()` was called, via a reference type so a `let`
/// (immutable, value-type) `FakePasteboard` can still record it.
private final class ReadFlag { var read = false }

private struct FakePasteboard: PasteboardReading {
    var changeCount = 1
    var types: [String] = ["public.utf8-plain-text"]
    var files: [URL] = []
    var image: PasteboardImage? = nil
    var color: String? = nil
    var text: String? = nil
    var rtfData: Data? = nil
    let rtfFlag = ReadFlag()
    /// When true, every read method fails the test: proves capture vetoes
    /// BEFORE touching any content, not just that it discards what it read.
    var failOnRead = false
    func fileURLs() -> [URL] { if failOnRead { XCTFail("content read on a vetoed change") }; return files }
    func imagePNG() -> PasteboardImage? { if failOnRead { XCTFail("content read on a vetoed change") }; return image }
    func colorHex() -> String? { if failOnRead { XCTFail("content read on a vetoed change") }; return color }
    func string() -> String? { if failOnRead { XCTFail("content read on a vetoed change") }; return text }
    func rtf() -> Data? { if failOnRead { XCTFail("content read on a vetoed change") }; rtfFlag.read = true; return rtfData }
}

private func ctx(excluded: [String] = [], paused: Bool = false, own: Int? = nil, front: String? = "com.apple.Notes") -> CaptureContext {
    var s = ClipboardSettings()
    s.excludedBundleIDs = excluded
    s.paused = paused
    return CaptureContext(frontBundleID: front, frontAppName: "Notes", settings: s, ownChangeCount: own)
}

final class ClipCaptureTests: XCTestCase {
    func testVetoConcealedTransientAndAutoGenerated() {
        for t in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
            XCTAssertEqual(CaptureVeto.reason(types: ["public.utf8-plain-text", t], changeCount: 1, context: ctx()), .concealed, t)
        }
    }

    func testVetoExcludedAppPausedAndOwnPaste() {
        XCTAssertEqual(CaptureVeto.reason(types: [], changeCount: 1, context: ctx(excluded: ["com.apple.Notes"])), .excludedApp)
        XCTAssertEqual(CaptureVeto.reason(types: [], changeCount: 1, context: ctx(paused: true)), .paused)
        XCTAssertEqual(CaptureVeto.reason(types: [], changeCount: 7, context: ctx(own: 7)), .ownPaste)
        XCTAssertNil(CaptureVeto.reason(types: [], changeCount: 8, context: ctx(own: 7)))
        XCTAssertNil(CaptureVeto.reason(types: [], changeCount: 1, context: ctx(excluded: ["com.other"], front: nil)))
    }

    func testCapturesTextWithSourceAndTitle() {
        let pb = FakePasteboard(text: "hello\nworld")
        let c = ClipCapture.capture(from: pb, context: ctx(), now: Date(timeIntervalSince1970: 100))!
        XCTAssertEqual(c.clip.kind, .text)
        XCTAssertEqual(c.clip.title, "hello")
        XCTAssertEqual(c.clip.payload, .text("hello\nworld"))
        XCTAssertEqual(c.clip.sourceAppName, "Notes")
        XCTAssertEqual(c.clip.sourceBundleID, "com.apple.Notes")
        XCTAssertEqual(c.clip.capturedAt, Date(timeIntervalSince1970: 100))
        XCTAssertNil(c.blobData)
    }

    func testFilesWinOverText() {
        let pb = FakePasteboard(files: [URL(fileURLWithPath: "/tmp/a.mov")], text: "/tmp/a.mov")
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .video)
        XCTAssertEqual(c.clip.payload, .fileURLs([URL(fileURLWithPath: "/tmp/a.mov")]))
        XCTAssertEqual(c.clip.title, "a.mov")
    }

    /// No string at all on the pasteboard (a screenshot, Preview, etc.):
    /// the image is the only usable content, so it wins.
    func testImageProducesBlobPayloadAndData() {
        let png = Data([0x89, 0x50, 0x4E, 0x47])
        let pb = FakePasteboard(image: PasteboardImage(data: png, width: 10, height: 20))
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .image)
        XCTAssertEqual(c.clip.title, "Image 10×20")
        XCTAssertEqual(c.blobData, png)
        guard case .blob(let id, let ut, let w, let h) = c.clip.payload else { return XCTFail() }
        XCTAssertEqual(id, c.clip.id); XCTAssertEqual(ut, "public.png"); XCTAssertEqual(w, 10); XCTAssertEqual(h, 20)
    }

    /// Word/Pages/Mail put a bitmap rendering of a text selection on the
    /// pasteboard alongside the text (and RTF); real text content must win.
    func testTextWithImageRenderingPrefersText() {
        let pb = FakePasteboard(types: ["public.utf8-plain-text", "public.rtf", "public.tiff"],
                                image: PasteboardImage(data: Data([1, 2, 3]), width: 748, height: 866),
                                text: "01 Contents\nExecutive summary")
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .text)
        XCTAssertEqual(c.clip.payload, .text("01 Contents\nExecutive summary"))
        XCTAssertNil(c.blobData)
    }

    /// A browser's "Copy Image" puts the image plus its bare URL as the
    /// string (no rich-text type) — the image should still win there.
    func testImageWithOnlyItsURLStaysImage() {
        let png = Data([1, 2, 3])
        let pb = FakePasteboard(types: ["public.tiff", "public.utf8-plain-text"],
                                image: PasteboardImage(data: png, width: 5, height: 5),
                                text: "https://example.com/a.png")
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .image)
        XCTAssertEqual(c.blobData, png)
    }

    /// A bare URL that DOES have a rich-text type alongside it is real text
    /// content (e.g. a link copied from a document), not a browser image
    /// export — text wins even though it classifies as .link.
    func testLinkTextWithRTFPrefersText() {
        let pb = FakePasteboard(types: ["public.utf8-plain-text", "public.rtf", "public.tiff"],
                                image: PasteboardImage(data: Data([1, 2, 3]), width: 5, height: 5),
                                text: "https://example.com")
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .link)
        XCTAssertNil(c.blobData)
    }

    func testTextWithRTFCarriesRichText() {
        let rtf = Data("{\\rtf1 hello}".utf8)
        let pb = FakePasteboard(types: ["public.utf8-plain-text", "public.rtf"],
                                text: "hello formatted", rtfData: rtf)
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .text)
        XCTAssertEqual(c.clip.richText, rtf)
    }

    func testOversizedRTFIsDroppedButTextKept() {
        let huge = Data(repeating: 0x41, count: 1_500_000)
        let pb = FakePasteboard(types: ["public.utf8-plain-text", "public.rtf"],
                                text: "big", rtfData: huge)
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .text)
        XCTAssertEqual(c.clip.payload, .text("big"))
        XCTAssertNil(c.clip.richText)
    }

    func testImageCopyDoesNotReadRTF() {
        let pb = FakePasteboard(image: PasteboardImage(data: Data([1, 2, 3]), width: 5, height: 5))
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .image)
        XCTAssertFalse(pb.rtfFlag.read)
    }

    func testSameImageBytesProduceSameIdDifferentBytesDiffer() {
        let pb1 = FakePasteboard(changeCount: 1, image: PasteboardImage(data: Data([1, 2, 3]), width: 1, height: 1))
        let pb2 = FakePasteboard(changeCount: 2, image: PasteboardImage(data: Data([1, 2, 3]), width: 1, height: 1))
        let c1 = ClipCapture.capture(from: pb1, context: ctx())!
        let c2 = ClipCapture.capture(from: pb2, context: ctx())!
        XCTAssertEqual(c1.clip.id, c2.clip.id)
        XCTAssertEqual(c1.clip.payload, c2.clip.payload)

        let pb3 = FakePasteboard(changeCount: 1, image: PasteboardImage(data: Data([1, 2, 4]), width: 1, height: 1))
        let c3 = ClipCapture.capture(from: pb3, context: ctx())!
        XCTAssertNotEqual(c1.clip.id, c3.clip.id)
    }

    func testColorObjectBecomesHexTextClip() {
        let pb = FakePasteboard(color: "#FF0080", text: nil)
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .color)
        XCTAssertEqual(c.clip.payload, .text("#FF0080"))
        XCTAssertEqual(c.clip.title, "#FF0080")
    }

    func testColorStringIsNormalised() {
        let c = ClipCapture.capture(from: FakePasteboard(text: "rgb(255,0,128)"), context: ctx())!
        XCTAssertEqual(c.clip.kind, .color)
        XCTAssertEqual(c.clip.payload, .text("#FF0080"))
    }

    func testUnnormalisableColorFunctionFallsBackToText() {
        let c = ClipCapture.capture(from: FakePasteboard(text: "hsl(330, 100%, 50%)"), context: ctx())!
        XCTAssertEqual(c.clip.kind, .text)
        XCTAssertEqual(c.clip.payload, .text("hsl(330, 100%, 50%)"))
        XCTAssertEqual(c.clip.title, "hsl(330, 100%, 50%)")
    }

    func testEmptyPasteboardOrWhitespaceIsNil() {
        XCTAssertNil(ClipCapture.capture(from: FakePasteboard(text: nil), context: ctx()))
        XCTAssertNil(ClipCapture.capture(from: FakePasteboard(text: "   "), context: ctx()))
    }

    func testHugeTextIsTruncatedToOneMegabyte() {
        let big = String(repeating: "a", count: 5_000_000)
        let pb = FakePasteboard(text: "first line\n" + big)
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .text)
        XCTAssertEqual(c.clip.title, "first line")
        guard case .text(let payload) = c.clip.payload else { return XCTFail("expected .text payload") }
        XCTAssertLessThanOrEqual(payload.utf8.count, ClipCapture.maxInlineTextBytes + 3)
        XCTAssertTrue(payload.hasSuffix("…"))
    }

    func testVetoedChangeIsNil() {
        XCTAssertNil(ClipCapture.capture(
            from: FakePasteboard(types: ["org.nspasteboard.ConcealedType"], text: "secret", failOnRead: true),
            context: ctx()))
        XCTAssertNil(ClipCapture.capture(
            from: FakePasteboard(text: "secret", failOnRead: true),
            context: ctx(excluded: ["com.apple.Notes"])))
        XCTAssertNil(ClipCapture.capture(
            from: FakePasteboard(text: "secret", failOnRead: true),
            context: ctx(paused: true)))
    }
}
