// Tests/ImperumCoreTests/ClipCaptureTests.swift
import XCTest
@testable import ImperumCore

private struct FakePasteboard: PasteboardReading {
    var changeCount = 1
    var types: [String] = ["public.utf8-plain-text"]
    var files: [URL] = []
    var image: PasteboardImage? = nil
    var color: String? = nil
    var text: String? = nil
    func fileURLs() -> [URL] { files }
    func imagePNG() -> PasteboardImage? { image }
    func colorHex() -> String? { color }
    func string() -> String? { text }
}

private func ctx(excluded: [String] = [], paused: Bool = false, own: Int? = nil, front: String? = "com.apple.Notes") -> CaptureContext {
    var s = ClipboardSettings()
    s.excludedBundleIDs = excluded
    s.paused = paused
    return CaptureContext(frontBundleID: front, frontAppName: "Notes", settings: s, ownChangeCount: own)
}

final class ClipCaptureTests: XCTestCase {
    func testVetoConcealedTransientAndAutoGenerated() {
        for t in ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"] {
            XCTAssertEqual(CaptureVeto.reason(types: ["public.utf8-plain-text", t], changeCount: 1, context: ctx()), .concealed, t)
        }
    }

    func testVetoExcludedAppPausedAndOwnPaste() {
        XCTAssertEqual(CaptureVeto.reason(types: [], changeCount: 1, context: ctx(excluded: ["com.apple.Notes"])), .excludedApp)
        XCTAssertEqual(CaptureVeto.reason(types: [], changeCount: 1, context: ctx(paused: true)), .paused)
        XCTAssertEqual(CaptureVeto.reason(types: [], changeCount: 7, context: ctx(own: 7)), .ownPaste)
        XCTAssertNil(CaptureVeto.reason(types: [], changeCount: 8, context: ctx(own: 7)))
        XCTAssertNil(CaptureVeto.reason(types: [], changeCount: 1, context: ctx(excluded: ["com.other"], front: nil)))
    }

    func testCapturesTextWithSourceAndTitle() {
        let pb = FakePasteboard(text: "hello\nworld")
        let c = ClipCapture.capture(from: pb, context: ctx(), now: Date(timeIntervalSince1970: 100))!
        XCTAssertEqual(c.clip.kind, .text)
        XCTAssertEqual(c.clip.title, "hello")
        XCTAssertEqual(c.clip.payload, .text("hello\nworld"))
        XCTAssertEqual(c.clip.sourceAppName, "Notes")
        XCTAssertEqual(c.clip.sourceBundleID, "com.apple.Notes")
        XCTAssertEqual(c.clip.capturedAt, Date(timeIntervalSince1970: 100))
        XCTAssertNil(c.blobData)
    }

    func testFilesWinOverText() {
        let pb = FakePasteboard(files: [URL(fileURLWithPath: "/tmp/a.mov")], text: "/tmp/a.mov")
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .video)
        XCTAssertEqual(c.clip.payload, .fileURLs([URL(fileURLWithPath: "/tmp/a.mov")]))
        XCTAssertEqual(c.clip.title, "a.mov")
    }

    func testImageProducesBlobPayloadAndData() {
        let png = Data([0x89, 0x50, 0x4E, 0x47])
        let pb = FakePasteboard(image: PasteboardImage(data: png, width: 10, height: 20), text: "ignored")
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .image)
        XCTAssertEqual(c.clip.title, "Image 10×20")
        XCTAssertEqual(c.blobData, png)
        guard case .blob(let id, let ut, let w, let h) = c.clip.payload else { return XCTFail() }
        XCTAssertEqual(id, c.clip.id); XCTAssertEqual(ut, "public.png"); XCTAssertEqual(w, 10); XCTAssertEqual(h, 20)
    }

    func testColorObjectBecomesHexTextClip() {
        let pb = FakePasteboard(color: "#FF0080", text: nil)
        let c = ClipCapture.capture(from: pb, context: ctx())!
        XCTAssertEqual(c.clip.kind, .color)
        XCTAssertEqual(c.clip.payload, .text("#FF0080"))
        XCTAssertEqual(c.clip.title, "#FF0080")
    }

    func testColorStringIsNormalised() {
        let c = ClipCapture.capture(from: FakePasteboard(text: "rgb(255,0,128)"), context: ctx())!
        XCTAssertEqual(c.clip.kind, .color)
        XCTAssertEqual(c.clip.payload, .text("#FF0080"))
    }

    func testEmptyPasteboardOrWhitespaceIsNil() {
        XCTAssertNil(ClipCapture.capture(from: FakePasteboard(text: nil), context: ctx()))
        XCTAssertNil(ClipCapture.capture(from: FakePasteboard(text: "   "), context: ctx()))
    }

    func testVetoedChangeIsNil() {
        XCTAssertNil(ClipCapture.capture(from: FakePasteboard(types: ["org.nspasteboard.ConcealedType"], text: "secret"), context: ctx()))
    }
}
