// Sources/ImperumCore/ClipCapture.swift
import CryptoKit
import Foundation

/// The subset of NSPasteboard the capture pipeline needs, so the pipeline
/// can be driven by a fake in tests. `ImperumTool` implements it on
/// `NSPasteboard.general`.
public protocol PasteboardReading {
    var changeCount: Int { get }
    var types: [String] { get }
    /// The types of each pasteboard item, in order (`types` is the flattened
    /// union). A native screenshot copy is exactly one item, `["public.png"]`.
    var itemTypes: [[String]] { get }
    func fileURLs() -> [URL]
    func imagePNG() -> PasteboardImage?
    func string() -> String?
    /// RTF bytes for `public.rtf`, if present. `ImperumTool`'s reader
    /// returns nil for RTFD-with-attachments (`com.apple.flat-rtfd`
    /// only) — out of scope for now.
    func rtf() -> Data?
}

public struct PasteboardImage: Equatable {
    public var data: Data
    public var width: Int
    public var height: Int
    public init(data: Data, width: Int, height: Int) { self.data = data; self.width = width; self.height = height }
}

public struct CaptureContext {
    public var frontBundleID: String?
    public var frontAppName: String
    public var settings: ClipboardSettings
    /// The change count our own paste produced, so it is not re-recorded.
    public var ownChangeCount: Int?
    public init(frontBundleID: String?, frontAppName: String, settings: ClipboardSettings, ownChangeCount: Int?) {
        self.frontBundleID = frontBundleID; self.frontAppName = frontAppName
        self.settings = settings; self.ownChangeCount = ownChangeCount
    }
}

public enum VetoReason: Equatable { case concealed, excludedApp, excludedHost(String), paused, ownPaste }

public enum CaptureVeto {
    public static let secretTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
    ]

    /// Evaluated BEFORE any content is read. `frontPageHost` is only called
    /// when `excludedHosts` is non-empty, since it may involve an
    /// Accessibility round-trip.
    public static func reason(types: [String], changeCount: Int, context: CaptureContext,
                               excludedHosts: [String] = [], frontPageHost: () -> String? = { nil }) -> VetoReason? {
        if types.contains(where: secretTypes.contains) { return .concealed }
        if let own = context.ownChangeCount, own == changeCount { return .ownPaste }
        if context.settings.paused { return .paused }
        if let b = context.frontBundleID, context.settings.excludedBundleIDs.contains(b) { return .excludedApp }
        if !excludedHosts.isEmpty, let host = frontPageHost(), HostExclusion.matches(host: host, entries: excludedHosts) {
            return .excludedHost(host)
        }
        return nil
    }
}

public struct CapturedClip: Equatable {
    public var clip: Clip
    /// PNG bytes for image clips; the caller writes them to the archive.
    public var blobData: Data?
    public init(clip: Clip, blobData: Data?) { self.clip = clip; self.blobData = blobData }
}

public enum ClipCapture {
    /// Inline text clips are capped at this many UTF-8 bytes at capture
    /// time. The index (all clips, text inline) is encoded and saved on a
    /// 500 ms debounce; an unbounded string (e.g. a huge log paste) made
    /// that save slow enough to stall the event tap's run loop.
    public static let maxInlineTextBytes = 1_000_000

    /// Truncates `s` to at most `maxInlineTextBytes` UTF-8 bytes, cutting at
    /// a character boundary and appending "…" when a cut was made.
    private static func truncatedIfNeeded(_ s: String) -> String {
        guard s.utf8.count > maxInlineTextBytes else { return s }
        var end = s.startIndex
        var bytes = 0
        for i in s.indices {
            let charBytes = s[i].utf8.count
            guard bytes + charBytes <= maxInlineTextBytes else { break }
            bytes += charBytes
            end = s.index(after: i)
        }
        return String(s[s.startIndex..<end]) + "…"
    }

    /// Derives a stable id from content bytes, so identical images dedupe
    /// the same way identical text does (`ClipContentKey` compares the
    /// `.blob` payload, id included).
    public static func contentID(_ data: Data) -> UUID {
        let digest = SHA256.hash(data: data)
        let bytes = Array(digest.prefix(16))
        return UUID(uuid: (bytes[0], bytes[1], bytes[2], bytes[3], bytes[4], bytes[5], bytes[6], bytes[7],
                            bytes[8], bytes[9], bytes[10], bytes[11], bytes[12], bytes[13], bytes[14], bytes[15]))
    }

    /// Pasteboard types that mean "this string is real rich-text content",
    /// not just a browser image export's incidental URL string.
    private static let richTextTypes: Set<String> = ["public.rtf", "com.apple.flat-rtfd"]

    /// An RTF companion is capped at this many bytes; above it the plain
    /// text is still captured, just without formatting.
    public static let maxRichTextBytes = 1_000_000

    /// The RTF companion for a text-family clip, or nil. Only consulted on
    /// the text-wins path — never for a bare-URL image export, a file, or an
    /// image, since none of those paths call this.
    private static func richTextIfPresent(from pb: PasteboardReading) -> Data? {
        guard pb.types.contains("public.rtf") else { return nil }
        guard let data = pb.rtf(), data.count <= maxRichTextBytes else { return nil }
        return data
    }

    /// Richest representation first: files → text-vs-image → string. Round
    /// 10: colour is no longer a distinct kind (`ClipClassifier.classifyText`
    /// never returns `.color`) — a colour-shaped string is just `.text`, and
    /// there is no longer a colour-object pasteboard type to read.
    ///
    /// Word, Pages, Mail and browsers (on a text selection) put a bitmap
    /// rendering of the selection on the pasteboard alongside the text (and
    /// often RTF); reading the image before the string used to capture that
    /// rendering as an `.image` clip instead of the text. The string is now
    /// read first and wins over any image UNLESS it's a bare URL with no
    /// rich-text type present — that shape (string + image, no RTF) is how
    /// browsers represent "Copy Image", where the string is just the
    /// image's URL, not real text content. With no string at all
    /// (screenshots, Preview), the image still wins as before.
    /// What `screencapture -c` (⌃⇧⌘3/4) puts on the pasteboard: one item whose
    /// only type is PNG. Browsers, Preview and Finder always add TIFF, HTML,
    /// URL or file-URL types, so this shape is a usable screenshot signature.
    public static func isScreenshotSignature(itemTypes: [[String]]) -> Bool {
        itemTypes.count == 1 && itemTypes[0] == ["public.png"]
    }

    public static let nativeScreenshotSource = (name: "Screenshot", bundle: "com.apple.screencapture")

    public static func capture(from pb: PasteboardReading, context: CaptureContext, now: Date = Date(),
                                excludedHosts: [String] = [], frontPageHost: () -> String? = { nil }) -> CapturedClip? {
        if CaptureVeto.reason(types: pb.types, changeCount: pb.changeCount, context: context,
                               excludedHosts: excludedHosts, frontPageHost: frontPageHost) != nil { return nil }
        let src = (name: context.frontAppName, bundle: context.frontBundleID)

        let files = pb.fileURLs()
        if !files.isEmpty {
            let kind = files.allSatisfy({ ClipClassifier.kindForFile($0) == .video }) ? ClipKind.video : .file
            return CapturedClip(clip: Clip(kind: kind, capturedAt: now, sourceAppName: src.name, sourceBundleID: src.bundle,
                                           title: ClipClassifier.title(forFiles: files), payload: .fileURLs(files)), blobData: nil)
        }

        let text = pb.string().map(truncatedIfNeeded)
        let textKind = text.flatMap(ClipClassifier.classifyText)
        let hasRichText = pb.types.contains(where: richTextTypes.contains)
        let isBareURLImageExport = textKind == .link && !hasRichText
        let textWinsOverImage = textKind != nil && !isBareURLImageExport

        if !textWinsOverImage, let img = pb.imagePNG() {
            let id = contentID(img.data)
            let payload = ClipPayload.blob(id: id, utType: "public.png", width: img.width, height: img.height)
            if isScreenshotSignature(itemTypes: pb.itemTypes) {
                let clip = Clip(id: id, kind: .screenshot, capturedAt: now,
                                sourceAppName: nativeScreenshotSource.name, sourceBundleID: nativeScreenshotSource.bundle,
                                title: ClipClassifier.title(screenshotWidth: img.width, height: img.height), payload: payload)
                return CapturedClip(clip: clip, blobData: img.data)
            }
            let clip = Clip(id: id, kind: .image, capturedAt: now, sourceAppName: src.name, sourceBundleID: src.bundle,
                            title: ClipClassifier.title(imageWidth: img.width, height: img.height), payload: payload)
            return CapturedClip(clip: clip, blobData: img.data)
        }
        guard let text, let kind = textKind else { return nil }
        return CapturedClip(clip: Clip(kind: kind, capturedAt: now, sourceAppName: src.name, sourceBundleID: src.bundle,
                                       title: ClipClassifier.title(forText: text), payload: .text(text),
                                       richText: richTextIfPresent(from: pb)), blobData: nil)
    }
}
