// Sources/ImperumCore/ClipCapture.swift
import Foundation

/// The subset of NSPasteboard the capture pipeline needs, so the pipeline
/// can be driven by a fake in tests. `ImperumTool` implements it on
/// `NSPasteboard.general`.
public protocol PasteboardReading {
    var changeCount: Int { get }
    var types: [String] { get }
    func fileURLs() -> [URL]
    func imagePNG() -> PasteboardImage?
    func colorHex() -> String?
    func string() -> String?
}

public struct PasteboardImage: Equatable {
    public var data: Data
    public var width: Int
    public var height: Int
    public init(data: Data, width: Int, height: Int) { self.data = data; self.width = width; self.height = height }
}

public struct CaptureContext {
    public var frontBundleID: String?
    public var frontAppName: String
    public var settings: ClipboardSettings
    /// The change count our own paste produced, so it is not re-recorded.
    public var ownChangeCount: Int?
    public init(frontBundleID: String?, frontAppName: String, settings: ClipboardSettings, ownChangeCount: Int?) {
        self.frontBundleID = frontBundleID; self.frontAppName = frontAppName
        self.settings = settings; self.ownChangeCount = ownChangeCount
    }
}

public enum VetoReason: Equatable { case concealed, excludedApp, paused, ownPaste }

public enum CaptureVeto {
    public static let secretTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
    ]

    /// Evaluated BEFORE any content is read.
    public static func reason(types: [String], changeCount: Int, context: CaptureContext) -> VetoReason? {
        if types.contains(where: secretTypes.contains) { return .concealed }
        if let own = context.ownChangeCount, own == changeCount { return .ownPaste }
        if context.settings.paused { return .paused }
        if let b = context.frontBundleID, context.settings.excludedBundleIDs.contains(b) { return .excludedApp }
        return nil
    }
}

public struct CapturedClip: Equatable {
    public var clip: Clip
    /// PNG bytes for image clips; the caller writes them to the archive.
    public var blobData: Data?
}

public enum ClipCapture {
    /// Richest representation first: files → image → colour → string.
    public static func capture(from pb: PasteboardReading, context: CaptureContext, now: Date = Date()) -> CapturedClip? {
        if CaptureVeto.reason(types: pb.types, changeCount: pb.changeCount, context: context) != nil { return nil }
        let src = (name: context.frontAppName, bundle: context.frontBundleID)

        let files = pb.fileURLs()
        if !files.isEmpty {
            let kind = files.allSatisfy({ ClipClassifier.kindForFile($0) == .video }) ? ClipKind.video : .file
            return CapturedClip(clip: Clip(kind: kind, capturedAt: now, sourceAppName: src.name, sourceBundleID: src.bundle,
                                           title: ClipClassifier.title(forFiles: files), payload: .fileURLs(files)), blobData: nil)
        }
        if let img = pb.imagePNG() {
            let id = UUID()
            let clip = Clip(id: id, kind: .image, capturedAt: now, sourceAppName: src.name, sourceBundleID: src.bundle,
                            title: ClipClassifier.title(imageWidth: img.width, height: img.height),
                            payload: .blob(id: id, utType: "public.png", width: img.width, height: img.height))
            return CapturedClip(clip: clip, blobData: img.data)
        }
        if let hex = pb.colorHex(), let norm = ClipClassifier.normalizedColorHex(hex) {
            return CapturedClip(clip: Clip(kind: .color, capturedAt: now, sourceAppName: src.name, sourceBundleID: src.bundle,
                                           title: norm, payload: .text(norm)), blobData: nil)
        }
        guard let text = pb.string(), let kind = ClipClassifier.classifyText(text) else { return nil }
        if kind == .color, let norm = ClipClassifier.normalizedColorHex(text) {
            return CapturedClip(clip: Clip(kind: .color, capturedAt: now, sourceAppName: src.name, sourceBundleID: src.bundle,
                                           title: norm, payload: .text(norm)), blobData: nil)
        }
        return CapturedClip(clip: Clip(kind: kind, capturedAt: now, sourceAppName: src.name, sourceBundleID: src.bundle,
                                       title: ClipClassifier.title(forText: text), payload: .text(text)), blobData: nil)
    }
}
